Repository H-uru/moul-assets, pull requests merged in 2021-04, with the labels that each got.

#24 VeeTsah LOC update
  compiled/dat/VeeTsah.loc
Labels: enhancement, objective

#27 Fix Relto dark hut problem in Windows 10 v2004+
  compiled/dat/Personal_District_psnlMYSTII.prp
Labels: bug, visual

#28 Fix Neighborhood clock globe animation.
  compiled/dat/Neighborhood_District_nb01.prp
Labels: bug, objective, visual
