Repository H-uru/moul-assets, pull requests merged in 2021-08, with the labels that each got.

#70 Updated Bahro Book image with corrected Yeesha symbol
  compiled/dat/GUI_District_bkBahroRockBook.prp
  sources/textures/tga/GUI/xBahroPageRock_Original.tga
  sources/textures/tga/GUI/xBahroPageRock_v3d.tga
Labels: visual, objective

#57 Er'cana Fix Rollup
  compiled/dat/Ercana_District_Canyon.prp
  compiled/dat/Ercana_District_PelletRm.prp
Labels: bug, technical, objective

#58 Fix Neighborhood fire marble SFX
  compiled/dat/Neighborhood_District_nb01.prp
  sources/Neighborhood/nb01Marbles.json
Labels: enhancement, objective

#54 Fix text scaling in the release notes dialog.
  compiled/dat/GUI_District_AdvancedGameSettingsDialog.prp
  compiled/dat/GUI_District_AudioSettingsDialog.prp
  compiled/dat/GUI_District_CalibrationGUI.prp
  compiled/dat/GUI_District_ContactSupportGUI.prp
  compiled/dat/GUI_District_GraphicsSettingsDialog.prp
  compiled/dat/GUI_District_IntroMovieGUI.prp
  compiled/dat/GUI_District_KIAgeOwnerSettings.prp
  compiled/dat/GUI_District_KIBlackBar.prp
  compiled/dat/GUI_District_KIHelp.prp
  compiled/dat/GUI_District_KIJournalExpanded.prp
  compiled/dat/GUI_District_KIMain.prp
  compiled/dat/GUI_District_KIMarkerFolder.prp
  compiled/dat/GUI_District_KIMarkerTimeMenu.prp
  compiled/dat/GUI_District_KIMicroBlackBar.prp
  compiled/dat/GUI_District_KIMini.prp
  compiled/dat/GUI_District_KINanoBlackBar.prp
  compiled/dat/GUI_District_KINewItemAlert.prp
  compiled/dat/GUI_District_KIPictureExpanded.prp
  compiled/dat/GUI_District_KIPlayerExpanded.prp
  compiled/dat/GUI_District_KIQuestionNote.prp
  compiled/dat/GUI_District_KIRateIt.prp
  compiled/dat/GUI_District_KISettings.prp
  compiled/dat/GUI_District_KIYesNo.prp
  compiled/dat/GUI_District_KeyMapDialog.prp
  compiled/dat/GUI_District_NavigationSettingsDialog.prp
  compiled/dat/GUI_District_OptionsMenuGUI.prp
  compiled/dat/GUI_District_OptionsMenuRestart.prp
  compiled/dat/GUI_District_OrientationGUI.prp
  compiled/dat/GUI_District_ReleaseNotesDialog.prp
  compiled/dat/GUI_District_StartupHelpGUI.prp
  compiled/dat/GUI_District_jalakControlPanel.prp
  sources/KI/xKIGUI.max
Labels: visual

#60 Re-export Fan02 clothing with PNG icons.
  compiled/dat/GlobalClothing_District_FemaleFan02.prp
  compiled/dat/GlobalClothing_District_MaleFan02.prp
Labels: enhancement

#72 Enlarged the black mask of the telescope for ultra-widescreen resolutions
  compiled/dat/GUI_District_telescope.prp
Labels: visual, objective

#73 Fixes for Ercana Canyon
  compiled/dat/Ercana_District_Canyon.prp
  compiled/dat/Ercana_District_PlantExterior01.prp
  compiled/dat/Ercana_District_Tunnel.prp
Labels: visual, objective

#32 Fix render issues with user-created GZ Markers
  compiled/dat/GlobalMarkers_District_Markers.prp
Labels: bug, visual
