Repository H-uru/moul-assets, pull requests merged in 2021-07, with the labels that each got.

#26 URL Confirmation Dialog Localization
  .gitattributes
  compiled/dat/KIEnglish.loc
Labels: enhancement

#56 Fix solid bendy bridge in Teledahn.
  compiled/dat/Teledahn_District_tldnHarvest.prp
Labels: bug, objective, technical

#55 Kadish moon elevator subworld no longer interacts with player
  compiled/dat/Kadish_District_kdshGlowInTheDark.prp
Labels: technical

#36 Add Serene Particle Effects
  compiled/dat/Serene_District_Snowfall.prp
  compiled/sfx/Serene_flocksndloop.ogg
Labels: enhancement, visual

#39 Adds Kadish Butterflies
  compiled/dat/Kadish_District_BuiltIn.prp
  compiled/dat/Kadish_District_KdshNoteGUI.prp
  compiled/dat/Kadish_District_Textures.prp
  compiled/dat/Kadish_District_kdshCourtyard.prp
  compiled/dat/Kadish_District_kdshForest.prp
  compiled/dat/Kadish_District_kdshGlowInTheDark.prp
  compiled/dat/Kadish_District_kdshPillars.prp
  compiled/dat/Kadish_District_kdshScope01.prp
  compiled/dat/Kadish_District_kdshScope02.prp
  compiled/dat/Kadish_District_kdshScope03.prp
  compiled/dat/Kadish_District_kdshShadowPath.prp
  compiled/dat/Kadish_District_kdshVaultExtr.prp
  compiled/dat/Kadish_District_kdshVaultExtrYeesha.prp
  compiled/dat/Kadish_District_kdshVaultIntr.prp
  compiled/dat/Kadish_District_kdshVaultIntrYeesha.prp
  compiled/dat/Kadish_District_kdshWalkView.prp
  compiled/dat/Kadish_District_kdshYeeshaExcerpts.prp
  compiled/dat/Kadish_District_kdshYeeshaExcerpts02.prp
  compiled/dat/Kadish_District_kdshYeeshaExcerpts03.prp
  compiled/dat/Kadish_District_kdshYeeshaExcerpts04.prp
  compiled/dat/Kadish_District_opt-kdshCourtyardPartLeaves.prp
  compiled/dat/Kadish_District_opt-kdshCourtyardPhysLeaves.prp
  compiled/dat/Kadish_District_opt-kdshCourtyardProjLights.prp
  compiled/dat/Kadish_District_opt-kdshWalkViewPartLeaves.prp
  compiled/dat/Kadish_District_opt-kdshWalkViewPhysLeaves.prp
  compiled/dat/Kadish_District_opt-kdshWalkViewProjLights.prp
Labels: enhancement, visual

#69 Fixes the Bahro Stone Linking Panel
  compiled/dat/GUI_District_BkBookImages.prp
  compiled/dat/GUI_District_bkBahroRockBook.prp
Labels: bug, global
