Repository H-uru/moul-assets, pull requests merged in 2021-02, with the labels that each got.

#19 [Teledahn] Fix spurious workroom noise.
  compiled/dat/Teledahn_District_tldnWorkroom.prp
Labels: bug, objective

#17 Watcher's Pub August 2020 Update
  compiled/dat/GreatTreePub_District_GreatTree.prp
  compiled/dat/GreatTreePub_District_Pub.prp
  compiled/dat/GreatTreePub_District_Textures.prp
  sources/GreatTreePub/GreatTreePub.blend
Labels: enhancement

#14 MOULa December 2020 Update
  compiled/dat/ChisoPreniv.loc
  compiled/dat/ChisoPreniv_District_Chiso.prp
  compiled/dat/ChisoPreniv_District_FanContent.prp
  compiled/dat/ChisoPreniv_District_Textures.prp
  compiled/dat/GoMePubNew.loc
  compiled/dat/GoMePubNew_District_Alcoves.prp
  compiled/dat/GoMePubNew_District_Entry.prp
  compiled/dat/GoMePubNew_District_GoMeConfRoom.prp
  compiled/dat/GoMePubNew_District_GoMePub.prp
  compiled/dat/GoMePubNew_District_Holidays.prp
  compiled/dat/GoMePubNew_District_StoreRoom.prp
  compiled/dat/GoMePubNew_District_Textures.prp
  compiled/dat/GoMePubNew_District_gmpnCones.prp
  compiled/dat/VeeTsah.loc
  compiled/dat/VeeTsah_District_Temple.prp
  compiled/dat/VeeTsah_District_Textures.prp
Labels: enhancement, subjective
