Repository H-uru/moul-assets, pull requests merged in 2021-05, with the labels that each got.

#20 Add Tre'bivdil to MOULa
  compiled/dat/trebivdil_District_BuiltIn.prp
  compiled/dat/trebivdil_District_Textures.prp
  compiled/dat/trebivdil_District_mainRoom.prp
  compiled/sfx/trbvl_waves_amb.ogg
Labels: enhancement

#23 Great Tree Pub March 2021 Updates
  compiled/dat/GreatTreePub_District_GreatTree.prp
  compiled/dat/GreatTreePub_District_Pub.prp
  compiled/dat/GreatTreePub_District_Textures.prp
  sources/GreatTreePub/GreatTreePub.blend
Labels: visual

#31 Fix clock globe turning backwards.
  compiled/dat/Neighborhood_District_BuiltIn.prp
  compiled/dat/Neighborhood_District_Classroom.prp
  compiled/dat/Neighborhood_District_CommonRoom.prp
  compiled/dat/Neighborhood_District_PrivateRm.prp
  compiled/dat/Neighborhood_District_Textures.prp
  compiled/dat/Neighborhood_District_nb01.prp
  compiled/dat/Neighborhood_District_nb01Ayhoheek5Man1Dead.prp
  compiled/dat/Neighborhood_District_nb01Ayhoheek5Man1State.prp
  compiled/dat/Neighborhood_District_nb01BahroPedestalShout.prp
  compiled/dat/Neighborhood_District_nb01ClockInfoSheetDlg.prp
  compiled/dat/Neighborhood_District_nb01DniPaper.prp
  compiled/dat/Neighborhood_District_nb01HNYVis.prp
  compiled/dat/Neighborhood_District_nb01LinkBookDelin.prp
  compiled/dat/Neighborhood_District_nb01LinkBookGarrisonVis.prp
  compiled/dat/Neighborhood_District_nb01LinkBookTeledahnVis.prp
  compiled/dat/Neighborhood_District_nb01LinkBookTsogal.prp
  compiled/dat/Neighborhood_District_nb01LiveAdditions.prp
  sources/textures/tga/Neighborhood/nb01ClockRefl_BK.tga
  sources/textures/tga/Neighborhood/nb01ClockRefl_DN.tga
  sources/textures/tga/Neighborhood/nb01ClockRefl_FR.tga
  sources/textures/tga/Neighborhood/nb01ClockRefl_LF.tga
  sources/textures/tga/Neighborhood/nb01ClockRefl_RT.tga
  sources/textures/tga/Neighborhood/nb01ClockRefl_UP.tga
  sources/textures/tga/Neighborhood/nb01clockrefl_BK.png
  sources/textures/tga/Neighborhood/nb01clockrefl_DN.png
  sources/textures/tga/Neighborhood/nb01clockrefl_FR.png
  sources/textures/tga/Neighborhood/nb01clockrefl_LF.png
  sources/textures/tga/Neighborhood/nb01clockrefl_RT.png
  sources/textures/tga/Neighborhood/nb01clockrefl_UP.png
Labels: bug, visual
