Repository H-uru/moul-assets, pull requests merged in 2022-12, with the labels that each got.

#178 Ahnonay Cathedral Q3 2022 Update
  compiled/dat/AhnonayCathedral_District_LinkRoom.prp
  compiled/dat/AhnonayCathedral_District_Textures.prp
  sources/Ahnonay Cathedral/AhnonayCathedral.blend
Labels: enhancement, blocking on moula

#181 Add Q42022 fan audio in English and French
  compiled/dat/Neighborhood02_District_krelCommonRm.prp
  compiled/sfx/krelFanQ42022_eng.ogg
  compiled/sfx/krelFanQ42022_eng.sub
  compiled/sfx/krelFanQ42022_fre.ogg
  compiled/sfx/krelFanQ42022_fre.sub
Labels: enhancement, subjective

#194 Add *.sub line to .gitattributes
  .gitattributes
Labels: enhancement, technical, objective

#193 Add EOL linter action.
  .github/lint_matchers.json
  .github/workflows/lint.yml
  eol.py
Labels: enhancement, technical

#184 Fix shading on the hydrant Cleft book in Relto
  compiled/dat/Personal_District_psnlMYSTII.prp
Labels: bug, visual, objective

#187 Cleft zandi radio fix
  compiled/sfx/clftZandiRadio_Loop.ogg
Labels: bug, technical, objective

#192 Phil Relto rain starts immediately
  compiled/dat/philRelto_District_PhilsRelto.prp
Labels: bug, visual, objective

#190 Adjust *.loc files to have LF line endings instead of CRLF
  compiled/dat/Serene.loc
  compiled/dat/Tiam.loc
  compiled/dat/VeeTsah.loc
Labels: bug, technical, objective

#185 Additional Cyan Trailer Cameras
  compiled/dat/Garden_District_trailerCamPage.prp
  compiled/dat/Garrison_District_trailerCamPage.prp
  compiled/dat/Neighborhood_District_trailerCamPage.prp
  compiled/dat/Personal_District_trailerCamPage.prp
  compiled/dat/Teledahn_District_trailerCamPage.prp
  compiled/dat/city_District_trailerCamPage.prp
Labels: enhancement

#191 Adjust Entry/Exit animations for Ahnonay Vogondola
  compiled/dat/Ahnonay_District_EngineerHut.prp
  compiled/dat/Ahnonay_District_Hub.prp
  compiled/dat/Ahnonay_District_Vortex.prp
Labels: bug, visual, objective

#195 Update Serene.loc for new journal contents
  compiled/dat/Serene.loc
Labels: enhancement, subjective
