Repository H-uru/moul-assets, pull requests merged in 2022-06, with the labels that each got.

#156 Add .vs folder to .gitignore file
  .gitignore
Labels: enhancement, technical, objective

#157 Increase dynamic text map viswidth and visheight for Atrus Note in Cleft
  compiled/dat/CleftEnglish.loc
  compiled/dat/CleftFrench.loc
  compiled/dat/Cleft_District_clftAtrusNote.prp
Labels: enhancement, visual, objective

#154 Remove dependency of Sharper's journal on non-localized dynamic text in the vault
  compiled/dat/BaronCityOfficeEnglish.loc
  compiled/dat/BaronCityOffice_District_BaronCityOffice.prp
Labels: enhancement, technical, objective

#114 Remove Visitor selection from Character selection screen
  compiled/dat/GUI_District_GUIDialog04b.prp
Labels: enhancement, visual

#160 Add localized audio tracks to AtrusIntro.webm
  compiled/avi/AtrusIntro.webm
Labels: enhancement, objective
