Repository H-uru/moul-assets, pull requests merged in 2022-05, with the labels that each got.

#133 Fixes Relto door animations to be centered in doorframe
  compiled/dat/Personal_District_psnlMYSTII.prp
Labels: bug, visual, objective

#132 Wall Game fixes
  compiled/dat/Garrison_District_NexusBlackRoom.prp
  compiled/dat/Garrison_District_NexusWhiteRoom.prp
  compiled/dat/Garrison_District_Textures.prp
  compiled/dat/Garrison_District_grsnWallRoomClimbingPhys.prp
Labels: bug, technical, objective

#134 Fix Relto Page sounds and missing python file mod options
  compiled/dat/GUI_District_IntroMovieGUI.prp
  compiled/dat/GUI_District_YeeshaPageGUI.prp
  sources/KI/xKIGUI.max
Labels: bug, technical, objective

#131 Add neutral possessive pronoun to use for receiver default in localized emotes
  compiled/dat/KIEnglish.loc
  compiled/dat/KIFrench.loc
  compiled/dat/KIGerman.loc
  compiled/dat/KIItalian.loc
  compiled/dat/KISpanish.loc
Labels: enhancement, global, objective

#136 Relto Door Animation fixes
  compiled/dat/Personal_District_psnlMYSTII.prp
Labels: bug, objective

#140 Add Tiam SFX
  compiled/sfx/TiamBtnShort.ogg
  compiled/sfx/TiamFirstHalfElfs3.ogg
  compiled/sfx/TiamKnappljud3.ogg
  compiled/sfx/TiamSten3.ogg
  compiled/sfx/TiamStenLoop3.ogg
  compiled/sfx/TiamWatLapping3.ogg
  compiled/sfx/Tiam_Liddown.ogg
  compiled/sfx/Tiam_Pling.ogg
  compiled/sfx/Tiam_Pling1.ogg
  compiled/sfx/Tiam_Pling2.ogg
  compiled/sfx/Tiam_button2.ogg
  compiled/sfx/Tiam_dblbuttnew.ogg
  compiled/sfx/Tiam_gitter.ogg
  compiled/sfx/Tiam_razzle2.ogg
  compiled/sfx/Tiam_wind.ogg
  compiled/sfx/Tiamwaterstream3.ogg
Labels: bug, objective

#101 Adding SRT files containing English audio subtitles
  compiled/sfx/bhroYeesha_GrdnSpeech_eng.sub
  compiled/sfx/bhroYeesha_GrsnSpeech_eng.sub
  compiled/sfx/bhroYeesha_KdshSpeech_eng.sub
  compiled/sfx/bhroYeesha_Speech01a_eng.sub
  compiled/sfx/bhroYeesha_Speech01b_eng.sub
  compiled/sfx/bhroYeesha_Speech02a_eng.sub
  compiled/sfx/bhroYeesha_Speech02b_eng.sub
  compiled/sfx/bhroYeesha_Speech03a_eng.sub
  compiled/sfx/bhroYeesha_Speech03b_eng.sub
  compiled/sfx/bhroYeesha_Speech04_eng.sub
  compiled/sfx/bhroYeesha_TldnSpeech_eng.sub
  compiled/sfx/clftEdog.sub
  compiled/sfx/clftEdog02.sub
  compiled/sfx/clftYeesha_IntroSp01_eng.sub
  compiled/sfx/clftYeesha_IntroSp02_eng.sub
  compiled/sfx/clftYeesha_TPOTS_Speech.sub
  compiled/sfx/clftZandiJC01a_eng.sub
  compiled/sfx/clftZandiJC01b_eng.sub
  compiled/sfx/clftZandiJC02a_eng.sub
  compiled/sfx/clftZandiJC02b_eng.sub
  compiled/sfx/clftZandiJC03a_eng.sub
  compiled/sfx/clftZandiJC03b_eng.sub
  compiled/sfx/clftZandiJC04a_eng.sub
  compiled/sfx/clftZandiJC04b_eng.sub
  compiled/sfx/clftZandiJC05a_eng.sub
  compiled/sfx/clftZandiJC05b_eng.sub
  compiled/sfx/clftZandiJC06a_eng.sub
  compiled/sfx/clftZandiJC06b_eng.sub
  compiled/sfx/clftZandiJC07a_eng.sub
  compiled/sfx/clftZandiJC07b_eng.sub
  compiled/sfx/clftZandiJCAll_eng.sub
  compiled/sfx/clftZandiMinRes01a_eng.sub
  compiled/sfx/clftZandiMinRes01b_eng.sub
  compiled/sfx/clftZandiMinRes02a_eng.sub
  compiled/sfx/clftZandiMinRes02b_eng.sub
  compiled/sfx/clftZandiMinRes03a_eng.sub
  compiled/sfx/clftZandiMinRes03b_eng.sub
  compiled/sfx/clftZandiOpen02a_eng.sub
  compiled/sfx/clftZandiRand01_eng.sub
  compiled/sfx/clftZandiRand02_eng.sub
  compiled/sfx/clftZandiRand03_eng.sub
  compiled/sfx/clftZandiRand04_eng.sub
  compiled/sfx/clftZandiRand05_eng.sub
  compiled/sfx/krelFanQ12022_eng.sub
  compiled/sfx/krelFanQ42021_eng.sub
  compiled/sfx/krelFanQ42021_fre.sub
  compiled/sfx/krelWatson_eng.sub
  compiled/sfx/tmnaYeesha_FinalSp01_eng.sub
  compiled/sfx/tmnaYeesha_FinalSp02_eng.sub
Labels: enhancement, global, technical, objective

#61 Update UruCredits journal.
  compiled/dat/GlobalEnglish.loc
Labels: documentation, enhancement

#147 KI chat context prefixes
  compiled/dat/KIEnglish.loc
  compiled/dat/KIFrench.loc
  compiled/dat/KIGerman.loc
  compiled/dat/KIItalian.loc
  compiled/dat/KISpanish.loc
Labels: enhancement, global
