Repository H-uru/moul-assets, pull requests merged in 2022-03, with the labels that each got.

#106 Fix nexus KI slot regions in City
  compiled/dat/city_District_canyon.prp
  compiled/dat/city_District_courtyard.prp
  compiled/dat/city_District_ferry.prp
  compiled/dat/city_District_palace.prp
Labels: bug, technical, objective

#109 Add single subtitle file for Zandi's Cleft intro as a testing sample
  compiled/sfx/clftZandiOpen01a_eng.sub
Labels: enhancement

#110 Remove triple-double-quote endings from Descent and Phil's Relto journals
  compiled/dat/DescentEnglish.loc
  compiled/dat/PhilReltoEnglish.loc
Labels: bug, objective

#111 Missing python file mod for pine tree collider
  compiled/dat/Personal_District_psnlMYSTII.prp
Labels: bug, technical, objective

#112 Fix GZ Beam in city
  compiled/dat/city_District_harbor.prp
Labels: bug, visual, objective

#108 Change PRP for options menu GUI to include Enable Subtitles checkbox
  compiled/dat/GUI_District_AdvancedGameSettingsDialog.prp
  compiled/dat/GUI_District_AudioSettingsDialog.prp
  compiled/dat/GUI_District_CalibrationGUI.prp
  compiled/dat/GUI_District_ContactSupportGUI.prp
  compiled/dat/GUI_District_GraphicsSettingsDialog.prp
  compiled/dat/GUI_District_IntroMovieGUI.prp
  compiled/dat/GUI_District_KIAgeOwnerSettings.prp
  compiled/dat/GUI_District_KIBlackBar.prp
  compiled/dat/GUI_District_KIHelp.prp
  compiled/dat/GUI_District_KIHelpMenu.prp
  compiled/dat/GUI_District_KIJournalExpanded.prp
  compiled/dat/GUI_District_KIListMode.prp
  compiled/dat/GUI_District_KIMain.prp
  compiled/dat/GUI_District_KIMarkerFolder.prp
  compiled/dat/GUI_District_KIMarkerTimeMenu.prp
  compiled/dat/GUI_District_KIMarkerTypeMenu.prp
  compiled/dat/GUI_District_KIMicro.prp
  compiled/dat/GUI_District_KIMicroBlackBar.prp
  compiled/dat/GUI_District_KIMini.prp
  compiled/dat/GUI_District_KIMiniMarkers.prp
  compiled/dat/GUI_District_KINanoBlackBar.prp
  compiled/dat/GUI_District_KINewItemAlert.prp
  compiled/dat/GUI_District_KIPictureExpanded.prp
  compiled/dat/GUI_District_KIPlayerExpanded.prp
  compiled/dat/GUI_District_KIQuestionNote.prp
  compiled/dat/GUI_District_KIRateIt.prp
  compiled/dat/GUI_District_KISettings.prp
  compiled/dat/GUI_District_KIVolumeSettings.prp
  compiled/dat/GUI_District_KIYesNo.prp
  compiled/dat/GUI_District_KeyMapDialog.prp
  compiled/dat/GUI_District_NavigationSettingsDialog.prp
  compiled/dat/GUI_District_OptionsMenuGUI.prp
  compiled/dat/GUI_District_OptionsMenuRestart.prp
  compiled/dat/GUI_District_OrientationGUI.prp
  compiled/dat/GUI_District_ReleaseNotesDialog.prp
  compiled/dat/GUI_District_StartupHelpGUI.prp
  compiled/dat/GUI_District_TrailerPreviewGUI.prp
  compiled/dat/GUI_District_jalakControlPanel.prp
  sources/KI/xKIGUI.max
Labels: enhancement, global

#100 Adds Backpack2 as a collectible in Dereno pod and correct Backpack model in Er'cana
  compiled/dat/Dereno_District_DrnoBackpack.prp
  compiled/dat/Ercana_District_Bakery.prp
  compiled/dat/Ercana_District_PlantExterior01.prp
  compiled/dat/Ercana_District_PlantExterior02.prp
Labels: enhancement, subjective, awaiting author
