Repository H-uru/moul-assets, pull requests merged in 2022-04, with the labels that each got.

#67 K'veer Update August 2021
  compiled/dat/Kveer_District_KveerHalls.prp
  compiled/dat/Kveer_District_Textures.prp
  sources/Kveer/Kveer.blend
Labels: technical, subjective

#94 Spyroom Q4 Updates
  compiled/dat/spyroom_District_Textures.prp
  compiled/dat/spyroom_District_spyroom.prp
  sources/spyroom/spyroom.blend
Labels: enhancement

#99 Adds the Cleft as a start choice at character creation
  compiled/avi/AtrusIntro.webm
  compiled/dat/Cleft_District_BookRoom.prp
  compiled/dat/Cleft_District_clftYeeshaBookVis.prp
  compiled/dat/GUIEnglish.loc
  compiled/dat/GUI_District_GUIDialog04d.prp
  compiled/dat/GUI_District_GUIDialog06.prp
  compiled/dat/GUI_District_KIMain.prp
  compiled/dat/GUI_District_KIPictureExpanded.prp
  compiled/dat/GUI_District_KIYesNo.prp
  compiled/dat/GUI_District_OrientationGUI.prp
  sources/KI/xKIGUI.max
  sources/KI/zandi.tga
Labels: enhancement, subjective

#119 Add /textcolor command and supporting text elements
  compiled/dat/GlobalEnglish.loc
  compiled/dat/GlobalFrench.loc
  compiled/dat/GlobalGerman.loc
  compiled/dat/GlobalItalian.loc
  compiled/dat/GlobalSpanish.loc
  compiled/dat/KIEnglish.loc
  compiled/dat/KIFrench.loc
  compiled/dat/KIGerman.loc
  compiled/dat/KIItalian.loc
  compiled/dat/KISpanish.loc
Labels: enhancement, global

#120 Add /cough and its emote string (plus translations)
  compiled/dat/KIEnglish.loc
  compiled/dat/KIFrench.loc
  compiled/dat/KIGerman.loc
  compiled/dat/KIItalian.loc
  compiled/dat/KISpanish.loc
Labels: global

#105 Adds back the Mantis Shirt and Sweatshirt
  compiled/dat/GlobalClothing_District_Female.prp
  compiled/dat/GlobalClothing_District_Female01.prp
  compiled/dat/GlobalClothing_District_Female02.prp
  compiled/dat/GlobalClothing_District_Female04.prp
  compiled/dat/GlobalClothing_District_FemaleFan01.prp
  compiled/dat/GlobalClothing_District_FemaleFan02.prp
  compiled/dat/GlobalClothing_District_FemaleGoL.prp
  compiled/dat/GlobalClothing_District_FemaleWizards.prp
  compiled/dat/GlobalClothing_District_Male.prp
  compiled/dat/GlobalClothing_District_Male01.prp
  compiled/dat/GlobalClothing_District_Male02.prp
  compiled/dat/GlobalClothing_District_Male04.prp
  compiled/dat/GlobalClothing_District_MaleFan01.prp
  compiled/dat/GlobalClothing_District_MaleFan02.prp
  compiled/dat/GlobalClothing_District_MaleGoL.prp
  compiled/dat/GlobalClothing_District_MaleWizards.prp
  sources/avatar/clothing/Avatar_Male02.max
  sources/avatar/clothing/Avatar_Male03.max
  sources/avatar/clothing/bas.avatar.female.01.max
  sources/avatar/clothing/bas.avatar.female.02.max
  sources/avatar/clothing/ftorso_mantis_base.tga
  sources/avatar/clothing/ftorso_mantis_tint1.tga
  sources/avatar/clothing/ftorso_mantis_tint2.tga
  sources/avatar/clothing/ftorso_sweatmantis_base.tga
  sources/avatar/clothing/ftorso_sweatmantis_tint1.tga
  sources/avatar/clothing/ftorso_sweatmantis_tint2.tga
  sources/avatar/clothing/icon_mtorso_mantis.tga
  sources/avatar/clothing/mtorso_mantis_base.tga
  sources/avatar/clothing/mtorso_mantis_tint1.tga
  sources/avatar/clothing/mtorso_mantis_tint2.tga
  sources/avatar/clothing/mtorso_sweatmantis_base.tga
  sources/avatar/clothing/mtorso_sweatmantis_tint1.tga
  sources/avatar/clothing/mtorso_sweatmantis_tint2.tga
Labels: bug, objective, blocking on moula

#113 Adds 2022-Q1 Kirel Podium audio
  compiled/dat/Neighborhood02_District_krelCommonRm.prp
  compiled/sfx/krelFanQ12022_eng.ogg
  compiled/sfx/krelFanQ12022_eng.sub
  compiled/sfx/krelFanQ12022_fre.ogg
  compiled/sfx/krelFanQ12022_fre.sub
  compiled/sfx/krelFanQ12022_ger.ogg
  compiled/sfx/krelFanQ12022_ger.sub
  compiled/sfx/krelFanQ42021_eng.ogg
  compiled/sfx/krelFanQ42021_fre.ogg
  compiled/sfx/krelFanQ42021_fre.sub
  compiled/sfx/krelFanQ42021_ger.ogg
  compiled/sfx/krelFanQ42021_ger.sub
  compiled/sfx/krelFanQ42021_ita.ogg
Labels: enhancement, subjective

#121 Add and fix possessive formatters for foreign languages
  compiled/dat/GlobalEnglish.loc
  compiled/dat/GlobalFrench.loc
  compiled/dat/GlobalGerman.loc
  compiled/dat/GlobalItalian.loc
  compiled/dat/GlobalSpanish.loc
  compiled/dat/KIEnglish.loc
  compiled/dat/KIFrench.loc
  compiled/dat/KIGerman.loc
  compiled/dat/KIItalian.loc
  compiled/dat/KISpanish.loc
Labels: bug, global

#124 Fix reference to stale DSpan object in Markers.
  compiled/dat/GlobalMarkers_District_Markers.prp
Labels: bug, technical, objective

#126 Add KI LOC strings, animation PRPs, and source max files for retro dance
  compiled/dat/GlobalAnimations_District_FemaleDanceRetro.prp
  compiled/dat/GlobalAnimations_District_MaleDanceRetro.prp
  compiled/dat/KIEnglish.loc
  compiled/dat/KIFrench.loc
  compiled/dat/KIGerman.loc
  compiled/dat/KIItalian.loc
  compiled/dat/KISpanish.loc
  sources/avatar/animations/FemaleDanceRetro.max
  sources/avatar/animations/MaleDanceRetro.max
Labels: enhancement, global, subjective

#127 Remove spaces in Spanish emote commands and guilt-trip in quit confirmation
  compiled/dat/KISpanish.loc
Labels: bug, objective

#116 Adds the cyan camera work done to create the trailer for Myst Online
  compiled/dat/Cleft_District_trailerCamPage.prp
Labels: enhancement

#122 Serene 2022 Q1 Updates
  compiled/dat/Serene_District_Textures.prp
  compiled/dat/Serene_District_mainRoom.prp
Labels: bug, objective

#130 Update Nexus LOCs
  compiled/dat/GlobalEnglish.loc
  compiled/dat/GlobalFrench.loc
  compiled/dat/GlobalGerman.loc
  compiled/dat/NexusEnglish.loc
  compiled/dat/NexusFrench.loc
  compiled/dat/NexusGerman.loc
  compiled/dat/NexusItalian.loc
  compiled/dat/NexusSpanish.loc
Labels: enhancement, global

#123 Chiso Pub Veelay Q12022 Updates
  compiled/dat/ChisoPreniv_District_Chiso.prp
  compiled/dat/ChisoPreniv_District_FanContent.prp
  compiled/dat/ChisoPreniv_District_Textures.prp
  compiled/dat/GoMePubNew_District_Alcoves.prp
  compiled/dat/GoMePubNew_District_Entry.prp
  compiled/dat/GoMePubNew_District_GoMeConfRoom.prp
  compiled/dat/GoMePubNew_District_GoMePub.prp
  compiled/dat/GoMePubNew_District_Holidays.prp
  compiled/dat/GoMePubNew_District_StoreRoom.prp
  compiled/dat/GoMePubNew_District_Textures.prp
  compiled/dat/GoMePubNew_District_gmpnCones.prp
  compiled/dat/VeeTsah.loc
Labels: enhancement, subjective
