Repository H-uru/moul-assets, pull requests merged in 2022-08, with the labels that each got.

#161 Add new audio, subtitles, and modified PRP for Kirel 2022-Q2 update message
  compiled/dat/Neighborhood02_District_krelCommonRm.prp
  compiled/sfx/krelFanQ22022_eng.ogg
  compiled/sfx/krelFanQ22022_eng.sub
  compiled/sfx/krelFanQ22022_fre.ogg
  compiled/sfx/krelFanQ22022_fre.sub
  compiled/sfx/krelFanQ22022_ger.ogg
  compiled/sfx/krelFanQ22022_ger.sub
Labels: enhancement, subjective

#159 Tiam Q2 2022 Update
  compiled/dat/Tiam_District_Default.prp
  compiled/dat/Tiam_District_Textures.prp
Labels: enhancement, subjective, blocking on moula

#146 Great Tree Pub/Watcher's Pub Q2 2022 Update
  compiled/dat/GreatTreePub_District_GreatTree.prp
  compiled/dat/GreatTreePub_District_Pub.prp
  compiled/dat/GreatTreePub_District_Textures.prp
Labels: enhancement, subjective

#138 ChisoPreniv Q2 2022
  compiled/dat/ChisoPreniv.loc
  compiled/dat/ChisoPreniv_District_Chiso.prp
  compiled/dat/ChisoPreniv_District_FanContent.prp
  compiled/dat/ChisoPreniv_District_LowerLevel.prp
  compiled/dat/ChisoPreniv_District_Textures.prp
Labels: enhancement, subjective, blocking on moula

#169 Update GoMePubNew Q2 2022
  compiled/dat/GoMePubNew.loc
  compiled/dat/GoMePubNew_District_Alcoves.prp
  compiled/dat/GoMePubNew_District_Entry.prp
  compiled/dat/GoMePubNew_District_GoMeConfRoom.prp
  compiled/dat/GoMePubNew_District_GoMePub.prp
  compiled/dat/GoMePubNew_District_Holidays.prp
  compiled/dat/GoMePubNew_District_Mysterium.prp
  compiled/dat/GoMePubNew_District_StoreRoom.prp
  compiled/dat/GoMePubNew_District_Textures.prp
  compiled/dat/GoMePubNew_District_gmpnCones.prp
Labels: enhancement, subjective

#173 Add highgarden
  compiled/dat/FahetsHighgardenEnglish.loc
  compiled/dat/FahetsHighgarden_District_BuiltIn.prp
  compiled/dat/FahetsHighgarden_District_Default.prp
  compiled/dat/FahetsHighgarden_District_Textures.prp
Labels: enhancement, subjective

#174 VeeTsah LOC updates
  compiled/dat/VeeTsah.loc
Labels: enhancement, objective
