Repository H-uru/moul-assets, pull requests merged in 2023-04, with the labels that each got.

#197 Q1 2023 clothing additions and changes
  compiled/dat/GlobalClothing_District_FemaleFan02.prp
  compiled/dat/GlobalClothing_District_FemaleMysterium.prp
  compiled/dat/GlobalClothing_District_MaleFan02.prp
  compiled/dat/GlobalClothing_District_MaleMysterium.prp
  sources/avatar/clothing_fan02/FLegs_Shorts_TransDye_Base.png
  sources/avatar/clothing_fan02/FTorso_HoodSweatCavernToday_Base.png
  sources/avatar/clothing_fan02/FTorso_HoodSweatCavernToday_Tint1.png
  sources/avatar/clothing_fan02/FTorso_HoodSweatCavernToday_Tint2.png
  sources/avatar/clothing_fan02/FTorso_HoodSweatMTP_Base.png
  sources/avatar/clothing_fan02/FTorso_HoodSweatMTP_Tint1.png
  sources/avatar/clothing_fan02/FTorso_LongSleeve_MTP_Base.png
  sources/avatar/clothing_fan02/FTorso_LongSleeve_MTP_Tint1.png
  sources/avatar/clothing_fan02/FTorso_ShortSleeve_Kalamee_Base.png
  sources/avatar/clothing_fan02/FTorso_ShortSleeve_Kalamee_Tint1.png
  sources/avatar/clothing_fan02/FTorso_ShortSleeve_MTP_Base.png
  sources/avatar/clothing_fan02/FTorso_ShortSleeve_MTP_Tint1.png
  sources/avatar/clothing_fan02/FTorso_xSleeve_CavernToday_Base.png
  sources/avatar/clothing_fan02/FTorso_xSleeve_CavernToday_Tint1.png
  sources/avatar/clothing_fan02/FTorso_xSleeve_CavernToday_Tint2.png
  sources/avatar/clothing_fan02/FTorso_xSleeve_GoInst_Tint1.png
  sources/avatar/clothing_fan02/FTorso_xSleeve_GoInst_base.png
  sources/avatar/clothing_fan02/Fan02.json
  sources/avatar/clothing_fan02/Icon_FLegs_shortstrydye.png
  sources/avatar/clothing_fan02/Icon_MLegs_shortstrydye.png
  sources/avatar/clothing_fan02/Icon_UTorso_Fleece_CavernToday.png
  sources/avatar/clothing_fan02/Icon_UTorso_Shirt_CavernToday.png
  sources/avatar/clothing_fan02/Icon_UTorso_Shirt_Kalamee.png
  sources/avatar/clothing_fan02/Icon_UTorso_Shirt_Mystitech.png
  sources/avatar/clothing_fan02/MLegs_Shorts_TransDye_Base.png
  sources/avatar/clothing_fan02/MTorso_Fleece_CavernToday_Base.png
  sources/avatar/clothing_fan02/MTorso_Fleece_CavernToday_Tint1.png
  sources/avatar/clothing_fan02/MTorso_HoodSweatCavernToday_Base.png
  sources/avatar/clothing_fan02/MTorso_HoodSweatCavernToday_Tint1.png
  sources/avatar/clothing_fan02/MTorso_HoodSweatCavernToday_Tint2.png
  sources/avatar/clothing_fan02/MTorso_HoodSweatMTP_Base.png
  sources/avatar/clothing_fan02/MTorso_HoodSweatMTP_Tint1.png
  sources/avatar/clothing_fan02/MTorso_ShortSleeve_Kalamee_Base.png
  sources/avatar/clothing_fan02/MTorso_ShortSleeve_Kalamee_Tint1.png
  sources/avatar/clothing_fan02/MTorso_xSleeve_CavernToday_Base.png
  sources/avatar/clothing_fan02/MTorso_xSleeve_CavernToday_Tint1.png
  sources/avatar/clothing_fan02/MTorso_xSleeve_CavernToday_Tint2.png
  sources/avatar/clothing_fan02/MTorso_xSleeve_GoInst_Tint1.png
  sources/avatar/clothing_fan02/MTorso_xSleeve_GoInst_base.png
  sources/avatar/clothing_fan02/MTorso_xSleeve_MTP_Base.png
  sources/avatar/clothing_fan02/MTorso_xSleeve_MTP_Tint1.png
  sources/avatar/clothing_mysterium/FTorso_ShortSleeve_Mysterium2023_Base.png
  sources/avatar/clothing_mysterium/FTorso_ShortSleeve_Mysterium2023_Tint1.png
  sources/avatar/clothing_mysterium/FTorso_ShortSleeve_Mysterium2023_Tint2.png
  sources/avatar/clothing_mysterium/FemaleSSMysterium.xcf
  sources/avatar/clothing_mysterium/Icon_UTorso_Shirt_Mysterium2023.png
  sources/avatar/clothing_mysterium/MTorso_ShortSleeve_Mysterium2023_Base.png
  sources/avatar/clothing_mysterium/MTorso_ShortSleeve_Mysterium2023_Tint1.png
  sources/avatar/clothing_mysterium/MTorso_ShortSleeve_Mysterium2023_Tint2.png
  sources/avatar/clothing_mysterium/MaleSSMysterium.xcf
  sources/avatar/clothing_mysterium/Mysterium Shirts/2023 MOULA shirt Female.png
  sources/avatar/clothing_mysterium/Mysterium Shirts/2023 MOULA shirt Male.png
  sources/avatar/clothing_mysterium/mysterium.json
Labels: enhancement, visual, global

#218 Fan Relto video to replace Yeesha intro
  .gitattributes
  compiled/avi/NewPlayerIntro.webm
  sources/avi/Relto23IntroEngFreGerFinal.mkv
Labels: enhancement, visual, global, subjective

#219 Fix some problems with Eder BS.
  compiled/dat/EderDelin_District_Textures.prp
  compiled/dat/EderDelin_District_garden.prp
  compiled/dat/EderTsogal_District_Textures.prp
  compiled/dat/EderTsogal_District_tsoGarden.prp
  sources/textures/tga/EderDelin/tsoenviro_BK.png
  sources/textures/tga/EderDelin/tsoenviro_DN.png
  sources/textures/tga/EderDelin/tsoenviro_FR.png
  sources/textures/tga/EderDelin/tsoenviro_LF.png
  sources/textures/tga/EderDelin/tsoenviro_RT.png
  sources/textures/tga/EderDelin/tsoenviro_UP.png
  sources/textures/tga/EderTsogal/tsoenviro_BK.png
  sources/textures/tga/EderTsogal/tsoenviro_DN.png
  sources/textures/tga/EderTsogal/tsoenviro_FR.png
  sources/textures/tga/EderTsogal/tsoenviro_LF.png
  sources/textures/tga/EderTsogal/tsoenviro_RT.png
  sources/textures/tga/EderTsogal/tsoenviro_UP.png
Labels: blocking on moula

#225 Fix Incorrect Textures In (Old) Messenger's Pub
  compiled/dat/GuildPub-Messengers_District_Textures.prp
  sources/textures/tga/GuildPub/gpmsTapestrySymbol_Corrected.png
Labels: bug, visual, objective

#227 Supplemental Update to PR224 (Phil's Relto Bookshelf)
  compiled/dat/philRelto_District_Textures.prp
  sources/textures/tga/PhilRelto/psnlBookCovers_philRelto.png
Labels: visual, objective
