Repository H-uru/moul-assets, pull requests merged in 2023-01, with the labels that each got.

#172 Garrison Updates to Match Moula Q2
  compiled/dat/Garrison_District_NexusBlackRoom.prp
  compiled/dat/Garrison_District_NexusWhiteRoom.prp
  compiled/dat/Garrison_District_WallAdditions.prp
  compiled/dat/Garrison_District_grsnObsRoom01Imager.prp
  compiled/dat/Garrison_District_grsnObsRoom02Imager.prp
  compiled/dat/Garrison_District_grsnWallRoomClimbingPhys.prp
  compiled/dat/Garrison_District_trainingCenterObservationRooms.prp
Labels: enhancement

#200 Textures added and changed to allow age reset mechanic from books
  compiled/dat/GUI_District_BkBookImages.prp
  sources/textures/tga/GUI/xBookmarkDniZero.tga
  sources/textures/tga/GUI/xBookmarkDniZero2.tga
Labels: enhancement

#189 Chiso Preniv Q3-4 2022 Updates
  compiled/dat/ChisoPreniv.loc
  compiled/dat/ChisoPreniv_District_Chiso.prp
  compiled/dat/ChisoPreniv_District_FanContent.prp
  compiled/dat/ChisoPreniv_District_LowerLevel.prp
  compiled/dat/ChisoPreniv_District_Textures.prp
Labels: enhancement, subjective

#205 Updated textures and fix texture bugs for bahro caves
  compiled/dat/LiveBahroCaves_District_BlueSpiralCave.prp
  compiled/dat/LiveBahroCaves_District_MINKcave.prp
  compiled/dat/LiveBahroCaves_District_PODcave.prp
  compiled/dat/LiveBahroCaves_District_POTScave.prp
  compiled/dat/LiveBahroCaves_District_Textures.prp
Labels: bug, visual, objective

#196 Add 2022 Q4 fan audio and subtitles in German
  compiled/dat/Neighborhood02_District_krelCommonRm.prp
  compiled/sfx/krelFanQ42022_ger.ogg
  compiled/sfx/krelFanQ42022_ger.sub
Labels: enhancement
