Repository H-uru/moul-assets, pull requests merged in 2023-02, with the labels that each got.

#208 Add Cannen Filter to Veelay Music
  compiled/sfx/psnlVeeTsahMusic.ogg
Labels: enhancement, subjective

#204 Restore DRC Stage functionality
  compiled/dat/city_District_ferry.prp
  compiled/dat/city_District_islmDRCStageState01.prp
  compiled/dat/city_District_islmDRCStageState02.prp
Labels: bug, technical, objective

#216 Forces Third Person camera when falling out of any bahro cave
  compiled/dat/LiveBahroCaves_District_BlueSpiralCave.prp
  compiled/dat/LiveBahroCaves_District_MINKcave.prp
  compiled/dat/LiveBahroCaves_District_PODcave.prp
  compiled/dat/LiveBahroCaves_District_POTScave.prp
Labels: bug, technical, objective

#203 Adjust Ahnonay waterfall loop to prevent sudden texture reset
  compiled/dat/Ahnonay_District_Vortex.prp
Labels: bug, visual, objective

#213 Fixes KI Light Sprite visibility in first person
  compiled/dat/GlobalAvatars_District_Female.prp
  compiled/dat/GlobalAvatars_District_Male.prp
  compiled/dat/GlobalClothing_District_Female.prp
  compiled/dat/GlobalClothing_District_FemaleFan02.prp
  compiled/dat/GlobalClothing_District_Male.prp
  compiled/dat/GlobalClothing_District_MaleFan02.prp
  sources/avatar/clothing/Avatar_Male01.max
  sources/avatar/clothing/bas.avatar.female.max
Labels: enhancement, visual

#198 Reverts Phil's Books to PotS/CC texture
  compiled/dat/philRelto_District_PhilsRelto.prp
  compiled/dat/philRelto_District_Textures.prp
Labels: visual, subjective
