Repository H-uru/moul-assets, pull requests merged in 2023-03, with the labels that each got.

#224 Adds Additional Updates to Phil's Relto Book Textures
  compiled/dat/philRelto_District_PhilsRelto.prp
  compiled/dat/philRelto_District_Textures.prp
Labels: visual, objective

#220 Add Chiso Preniv Book to Relto Bookshelf
  compiled/dat/GUI_District_BkBookImages.prp
  compiled/dat/PersonalEnglish.loc
  compiled/dat/PersonalFrench.loc
  compiled/dat/PersonalGerman.loc
  compiled/dat/PersonalItalian.loc
  compiled/dat/PersonalSpanish.loc
  compiled/dat/Personal_District_Textures.prp
  compiled/dat/Personal_District_psnlMYSTII.prp
Labels: enhancement

#221 GreatTreePub Update 2.15.2023
  compiled/dat/GlobalEnglish.loc
  compiled/dat/GlobalFrench.loc
  compiled/dat/GlobalGerman.loc
  compiled/dat/GlobalItalian.loc
  compiled/dat/GlobalSpanish.loc
  compiled/dat/GreatTreePub_District_GreatTree.prp
  compiled/dat/GreatTreePub_District_Pub.prp
  compiled/dat/GreatTreePub_District_Textures.prp
Labels: enhancement

#209 Wall Game fixes
  compiled/dat/Garrison_District_WallAdditions.prp
  compiled/dat/Garrison_District_WallRoom.prp
  compiled/dat/Garrison_District_grsnWallRoomClimbingPhys.prp
Labels: bug, technical, objective

#206 Add Video Selector buttons for Video Options Menu GUI
  compiled/dat/GUI_District_AdvancedGameSettingsDialog.prp
  compiled/dat/GUI_District_AudioSettingsDialog.prp
  compiled/dat/GUI_District_AvatarCustomization.prp
  compiled/dat/GUI_District_BkBook.prp
  compiled/dat/GUI_District_CalibrationGUI.prp
  compiled/dat/GUI_District_ContactSupportGUI.prp
  compiled/dat/GUI_District_GUIDialog04a.prp
  compiled/dat/GUI_District_GUIDialog04c.prp
  compiled/dat/GUI_District_GUIDialog05.prp
  compiled/dat/GUI_District_GUIDialog06a.prp
  compiled/dat/GUI_District_GUIDialog13.prp
  compiled/dat/GUI_District_GraphicsSettingsDialog.prp
  compiled/dat/GUI_District_IntroBahroBgGUI.prp
  compiled/dat/GUI_District_IntroMovieGUI.prp
  compiled/dat/GUI_District_KIAgeOwnerSettings.prp
  compiled/dat/GUI_District_KIBlackBar.prp
  compiled/dat/GUI_District_KIHelp.prp
  compiled/dat/GUI_District_KIJournalExpanded.prp
  compiled/dat/GUI_District_KIListMode.prp
  compiled/dat/GUI_District_KIMain.prp
  compiled/dat/GUI_District_KIMarkerFolder.prp
  compiled/dat/GUI_District_KIMicro.prp
  compiled/dat/GUI_District_KIMicroBlackBar.prp
  compiled/dat/GUI_District_KIMini.prp
  compiled/dat/GUI_District_KIMiniMarkers.prp
  compiled/dat/GUI_District_KINanoBlackBar.prp
  compiled/dat/GUI_District_KINewItemAlert.prp
  compiled/dat/GUI_District_KIPictureExpanded.prp
  compiled/dat/GUI_District_KIPlayerExpanded.prp
  compiled/dat/GUI_District_KIQuestionNote.prp
  compiled/dat/GUI_District_KIRateIt.prp
  compiled/dat/GUI_District_KISettings.prp
  compiled/dat/GUI_District_KIVolumeSettings.prp
  compiled/dat/GUI_District_KIYesNo.prp
  compiled/dat/GUI_District_KeyMapDialog.prp
  compiled/dat/GUI_District_NavigationSettingsDialog.prp
  compiled/dat/GUI_District_OptionsMenuGUI.prp
  compiled/dat/GUI_District_OptionsMenuRestart.prp
  compiled/dat/GUI_District_OrientationGUI.prp
  compiled/dat/GUI_District_ReleaseNotesDialog.prp
  compiled/dat/GUI_District_StartupHelpGUI.prp
  compiled/dat/GUI_District_TrailerPreviewGUI.prp
  compiled/dat/GUI_District_bkNotebook.prp
  compiled/dat/GUI_District_jalakControlPanel.prp
  compiled/dat/OptionsMenuEnglish.loc
  compiled/dat/OptionsMenuFrench.loc
  compiled/dat/OptionsMenuGerman.loc
  compiled/dat/OptionsMenuItalian.loc
  compiled/dat/OptionsMenuSpanish.loc
  sources/KI/xKIGUI.max
Labels: enhancement, global, subjective
