Repository H-uru/moul-assets, pull requests merged in 2024-11, with the labels that each got.

#266 FemaleHandsOptionsColorsFix
  compiled/dat/GlobalClothing_District_Female.prp
  sources/avatar/clothing/bas.avatar.female.max
Labels: technical, objective

#262 Fix Link Panel for Rainy Cleft
  compiled/dat/GUI_District_BkBookImages.prp
  sources/textures/tga/GUI/xLinkPanelTomahnaDesert.png
  sources/textures/tga/GUI/xLinkPanelTomahnaDesert.tga
Labels: visual, subjective

#263 Cleft Texture Improvements (Zandi Props & Skybox)
  compiled/dat/Cleft_District_Textures.prp
  sources/textures/tga/Cleft/clftBeerCan.png
  sources/textures/tga/Cleft/clftBeerCan.tga
  sources/textures/tga/Cleft/clftChipsBag.png
  sources/textures/tga/Cleft/clftChipsBag.tga
Labels: visual, subjective

#265 Bracelet Clothing
  compiled/dat/ACAEnglish.loc
  compiled/dat/ACAFrench.loc
  compiled/dat/ACAGerman.loc
  compiled/dat/ACAItalian.loc
  compiled/dat/ACASpanish.loc
  compiled/dat/GlobalClothing_District_FemaleBracelets.prp
  compiled/dat/GlobalClothing_District_MaleBracelets.prp
  sources/avatar/clothing_bracelets/Icon_UHand_Bracelet.png
  sources/avatar/clothing_bracelets/Icon_UHand_Bracelet.xcf
  sources/avatar/clothing_bracelets/UHand_Bracelet_tint1.png
  sources/avatar/clothing_bracelets/UHand_Bracelet_tint1.xcf
  sources/avatar/clothing_bracelets/bracelet_export_mesh.blend
  sources/avatar/clothing_bracelets/bracelet_export_mesh_f.blend
Labels: global, subjective

#242 Adds back the doors to the City
  compiled/dat/city_District_LibraryInterior.prp
  compiled/dat/city_District_MuseumInteriorPage.prp
  compiled/dat/city_District_library.prp
  compiled/dat/city_District_libraryDoors.prp
  compiled/dat/city_District_museumDoor.prp
Labels: enhancement, objective

#241 Add additional string option to Pellet Imager
  compiled/dat/Neighborhood_District_nb01.prp
Labels: enhancement, technical, objective

#261 Improve Green Storm Texture
  compiled/dat/Personal_District_Textures.prp
  sources/textures/tga/Personal/psnlnewsky3verydark_40#2.png
Labels: visual, subjective

#223 Add instructions for browsing using LFS cloning
  README.md
Labels: documentation, enhancement

#234 Add contributing guide.
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement

#271 Adjust Translations for "Big Blues" Attributions
  compiled/dat/GlobalFrench.loc
  compiled/dat/GlobalGerman.loc
  compiled/dat/GlobalItalian.loc
  compiled/dat/GlobalSpanish.loc
Labels: global, objective
